development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: simpultech_test_development

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV['REDIS_URL'] %>
  channel_prefix: simpultech_test_production
